### ISSUE TITLE
Add sort by recently accessed

### ISSUE THREAD

**Issue by justintime4tea** [justintime4tea/KeePass-Libre#9]
Add ability to sort by most recently accessed from the sort menu

**Comment by J-Jamet** [comment]
This is planned in KeePass DX, I'll also add an option to move the trash to the end. ;)

**Comment by justintime4tea** [comment]
Implemented by Jeremy and added to develop at commit:
0471dd3f8b289ebb058d250b64ca6b17d67322e8
